module.exports = {
    extends: [
        "airbnb-typescript",
        "airbnb/hooks",
        "plugin:@typescript-eslint/recommended",
        "prettier",
        "plugin:prettier/recommended",
        "plugin:react/recommended",
    ],
    env: {
        es6: true,
        jest: false,
    },
    parser: "@typescript-eslint/parser",
    parserOptions: {
        project: "tsconfig.json",
        sourceType: "module",
    },
    plugins: ["babel", "react", "@typescript-eslint", "import"],
    settings: {
        react: {
            version: "detect",
        },
    },
    rules: {
        "@typescript-eslint/array-type": [
            "warn",
            {
                default: "array-simple",
            },
        ],
        "@typescript-eslint/ban-ts-comment": "warn",
        "@typescript-eslint/ban-types": [
            "error",
            {
                types: {
                    Object: {
                        message: "Avoid using the `Object` type. Did you mean `object`?",
                    },
                    Function: {
                        message: "Avoid using the `Function` type. Prefer a specific function type, like `() => void`.",
                    },
                    Boolean: {
                        message: "Avoid using the `Boolean` type. Did you mean `boolean`?",
                    },
                    Number: {
                        message: "Avoid using the `Number` type. Did you mean `number`?",
                    },
                    String: {
                        message: "Avoid using the `String` type. Did you mean `string`?",
                    },
                    Symbol: {
                        message: "Avoid using the `Symbol` type. Did you mean `symbol`?",
                    },
                },
            },
        ],
        "@typescript-eslint/consistent-type-definitions": "off",
        "@typescript-eslint/dot-notation": "error",
        "@typescript-eslint/explicit-member-accessibility": "warn",
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/indent": "off",
        "@typescript-eslint/member-delimiter-style": [
            "off",
            {
                multiline: {
                    delimiter: "none",
                    requireLast: true,
                },
                singleline: {
                    delimiter: "semi",
                    requireLast: false,
                },
            },
        ],
        "@typescript-eslint/member-ordering": "off",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-inferrable-types": "off",
        "@typescript-eslint/no-parameter-properties": "off",
        "@typescript-eslint/no-shadow": "warn",
        "@typescript-eslint/no-unused-expressions": ["warn", { allowTaggedTemplates: true }],
        "@typescript-eslint/no-use-before-define": "off",
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",
        "@typescript-eslint/quotes": "off",
        "@typescript-eslint/semi": ["off", null],
        "@typescript-eslint/triple-slash-reference": [
            "error",
            {
                path: "always",
                types: "prefer-import",
                lib: "always",
            },
        ],
        "@typescript-eslint/type-annotation-spacing": "off",
        "@typescript-eslint/unified-signatures": "error",
        "jsx-a11y/anchor-is-valid": "off",
        "arrow-body-style": "warn",
        "arrow-parens": ["off", "always"],
        "brace-style": ["off", "off"],
        camelcase: "error",
        "class-methods-use-this": "warn",
        "comma-dangle": "off",
        complexity: "off",
        "constructor-super": "error",
        curly: "error",
        "default-case": "off", // handled by Typescript's noFallthroughCasesInSwitch
        "eol-last": "off",
        eqeqeq: ["error", "smart"],
        "guard-for-in": "error",
        "id-blacklist": [
            "error",
            "any",
            "Number",
            "number",
            "String",
            "string",
            "Boolean",
            "boolean",
            "Undefined",
            "undefined",
        ],
        "id-match": "error",
        "import/extensions": "off",
        "import/no-cycle": "warn",
        "import/no-duplicates": "warn",
        "import/no-useless-path-segments": "warn",
        "import/order": "off",
        "import/prefer-default-export": "off",
        "jsx-a11y/anchor-is-valid": "off",
        "linebreak-style": "off",
        "max-classes-per-file": ["error", 1],
        "max-len": "off",
        "new-parens": "off",
        "newline-per-chained-call": "off",
        "no-bitwise": "error",
        "no-caller": "error",
        "no-cond-assign": "error",
        "no-console": "error",
        "no-continue": "off",
        "no-debugger": "error",
        "no-else-return": "off",
        "no-empty": "off",
        "no-eval": "error",
        "no-extra-semi": "off",
        "no-fallthrough": "error",
        "no-invalid-this": "error",
        "no-irregular-whitespace": "off",
        "no-multiple-empty-lines": "off",
        "no-nested-ternary": "warn",
        "no-new-wrappers": "error",
        "no-param-reassign": ["error", { props: false }],
        "no-restricted-syntax": "off",
        "no-shadow": "off", // see @typescript-eslint/no-shadow
        "no-throw-literal": "error",
        "no-trailing-spaces": "off",
        "no-undef-init": "warn",
        "no-underscore-dangle": ["error", { allow: ["__typename"] }],
        "no-unsafe-finally": "error",
        "no-unused-labels": "error",
        "no-warning-comments": [
            "error",
            {
                terms: ["fixme"],
                location: "start",
            },
        ],
        "object-shorthand": "warn",
        "one-var": ["error", "never"],
        "operator-assignment": "warn",
        "prefer-const": "warn",
        "prefer-destructuring": ["warn", { object: true, array: false }],
        "quote-props": "off",
        radix: "error",
        "react/jsx-curly-brace-presence": "warn",
        "react/destructuring-assignment": "off",
        "react/display-name": "warn",
        "react/jsx-boolean-value": "off",
        "react/no-array-index-key": "warn",
        "react/no-unused-prop-types": "off",
        "react/prop-types": "off",
        "react/require-default-props": "off",
        "react/sort-comp": "off",
        "react/state-in-constructor": "warn",
        "react/static-property-placement": "warn",
        "space-before-function-paren": "off",
        "space-in-parens": ["off", "never"],
        "spaced-comment": [
            "error",
            "always",
            {
                markers: ["/"],
            },
        ],
        "use-isnan": "error",
    },
    reportUnusedDisableDirectives: true,
};
